# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Turso import test

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  schedule:
    - cron: '0 8 * * MON'
  workflow_dispatch:

jobs:

  turso_system:
        # env:
          # UV_CACHE_DIR: ${{ github.workspace }}/.cache/uv
          # UV_CACHE_DIR: /wrk-kappa/group/spacephysics/analysator/CI/.cache/uv
        if: github.repository_owner == 'fmihpc'
        runs-on: carrington
        strategy:
          fail-fast: false
          matrix:
            extras: ["none", "all", "bvtk"]
        steps:
        - uses: actions/checkout@v4
        - name: Install uv
          uses: astral-sh/setup-uv@v6
        # - name: Restore uv cache
        #   uses: actions/cache@v4
        #   with:
        #     path: /wrk-kappa/group/spacephysics/analysator/CI/.cache/uv
        #     key: uv-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
        #     restore-keys: |
        #       uv-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
        #       uv-${{ runner.os }}
            
        - name: Install dependencies
          run: |
            export TMPDIR=$RUNNER_TEMP
            uv venv CI_env
            . CI_env/bin/activate
            uv pip install --editable ../analysator[${{ matrix.extras }}]
        - name: Trial imports
          run: |
            export TMPDIR=$RUNNER_TEMP
            . CI_env/bin/activate
            python -c 'import analysator as pt'
            python -c 'import analysator as pt;pt.plot.__dict__'
            python -c 'import analysator as pt;pt.calculations.__dict__'
            python -c 'import analysator as pt;pt.vlsvfile.__dict__'
            python -c 'import analysator as pt;pt.miscellaneous.__dict__'

            
